apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test
spec:
  replicas: 150000
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test      
    spec:
      containers:
      - name: test
        image: kahootali/counter:1.0
        ports:
        - containerPort: 80
